services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fullstackops-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd!2026
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd!2026' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - fullstackops_sqlserver:/var/opt/mssql

volumes:
  fullstackops_sqlserver:
